INSERT INTO `[TABLE_NAME]` (`tmp_id`, `css`, `text`, `value`, `params`) VALUES
(1, 'left::32px||top::86px||width::160px||height::32px||color::rgb(235, 236, 195)||background-color::transparent||border::1px none rgb(235, 236, 195)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::700||text-align::left||text-transform::none||border-radius::0px', '138 Timber Creek Drive\nMemphis, TN 38018\n', '', 'tag::P||src::undefined||class::undefined||data::undefined||type::undefined'),
(1, 'left::31px||top::279px||width::118px||height::16px||color::rgb(67, 93, 27)||background-color::transparent||border::1px none rgb(67, 93, 27)||font-family::Arial,Helvetica,sans-serif||font-size::14px||font-weight::400||text-align::left||text-transform::none||border-radius::0px', 'Pick up the phone.', '', 'tag::LABEL||src::undefined||class::undefined||data::undefined||type::undefined'),
(1, 'left::33px||top::302px||width::104px||height::13px||color::rgb(234, 244, 226)||background-color::transparent||border::1px none rgb(234, 244, 226)||font-family::Arial,Helvetica,sans-serif||font-size::11px||font-weight::700||text-align::left||text-transform::none||border-radius::0px', 'Office: 901.757.8898', '', 'tag::LABEL||src::undefined||class::undefined||data::undefined||type::undefined'),
(1, 'left::260px||top::53px||width::94px||height::16px||color::rgb(91, 108, 56)||background-color::transparent||border::1px none rgb(91, 108, 56)||font-family::Arial,Helvetica,sans-serif||font-size::14px||font-weight::400||text-align::left||text-transform::none||border-radius::0px', 'Send an email.', '', 'tag::LABEL||src::undefined||class::undefined||data::undefined||type::undefined'),
(1, 'left::39px||top::232px||width::145px||height::14px||color::rgb(194, 208, 130)||background-color::transparent||border::1px none rgb(194, 208, 130)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::400||text-align::left||text-transform::none||border-radius::0px', 'View map & get directions.', '', 'tag::LABEL||src::undefined||class::undefined||data::undefined||type::undefined'),
(1, 'left::260px||top::76px||width::160px||height::24px||color::rgb(172, 204, 92)||background-color::rgb(255, 255, 160)||border::1px solid rgb(204, 204, 204)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::400||text-align::left||text-transform::none||border-radius::3px', '', '', 'tag::INPUT||src::undefined||class::required||data::undefined||type::text||placeholder::Name||||name::Name'),
(1, 'left::260px||top::117px||width::160px||height::24px||color::rgb(172, 204, 92)||background-color::rgb(255, 255, 160)||border::1px solid rgb(204, 204, 204)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::400||text-align::left||text-transform::none||border-radius::3px', '', '', 'tag::INPUT||src::undefined||class::required||data::undefined||type::email||placeholder::EmailAddress||||name::EmailAddress'),
(1, 'left::260px||top::160px||width::160px||height::24px||color::rgb(172, 204, 92)||background-color::rgb(255, 255, 160)||border::1px solid rgb(204, 204, 204)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::400||text-align::left||text-transform::none||border-radius::3px', '', '', 'tag::INPUT||src::undefined||class::undefined||data::undefined||type::text||placeholder::Phone||||name::Phone'),
(1, 'left::260px||top::196px||width::160px||height::82px||color::rgb(172, 201, 118)||background-color::rgb(255, 255, 255)||border::1px solid rgb(204, 204, 204)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::400||text-align::left||text-transform::none||border-radius::3px', '', '', 'tag::TEXTAREA||src::undefined||class::required||data::undefined||type::undefined||placeholder::Message||||name::Message'),
(1, 'left::260px||top::291px||width::54px||height::24px||color::rgb(165, 189, 121)||background-color::rgb(68, 94, 36)||border::1px solid rgb(93, 123, 44)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::400||text-align::center||text-transform::none||border-radius::4px', '', 'Submit.', 'tag::INPUT||src::undefined||class::undefined||data::undefined||type::submit||placeholder::||||name::field9_23'),
(1, 'left::33px||top::122px||width::158px||height::104px||color::rgb(51, 51, 51)||background-color::transparent||border::1px none rgb(51, 51, 51)||font-family::Arial,Helvetica,sans-serif||font-size::12px||font-weight::400||text-align::start||text-transform::none||border-radius::0px', '', '', 'tag::IMG||src::http://maps.googleapis.com/maps/api/staticmap?center=&zoom=1&size=158x104&maptype=terrain&sensor=false||class::map||data::undefined||type::undefined');
